title: Marielena Soilemezidi
logo: /assets/repository-MS_wug.png
description: **PhD student** in Linguistics at the National and Kapodistrian University of Athens (NKUA), <br/>Lab of Psycholinguistics and Neurolinguistics of NKUA, <br/>Greece <br/> & **Research Assistant** at the Center for Multilingualism Across the Lifespan (MultiLing), University of Oslo, <br/>Norway
theme: jekyll-theme-minimal
