theme: jekyll-theme-minimal
title: Marielena Soilemezidi
logo: /assets/img/repository-MS_wug.png
description: Current roles & affiliations_: - PhD student in Linguistics at the National and Kapodistrian University of Athens (NKUA), Lab of Psycholinguistics and Neurolinguistics of NKUA, Greece  - Research Assistant at the Center for Multilingualism Across the Lifespan (MultiLing), University of Oslo
show_downloads: false
google_analytics:
