theme: jekyll-theme-minimal
title: [Marielena Soilemezidi]
description: [<br/> ![wug](https://github.com/MarielenaS/personal-webpage/repository-MS_wug.png) <br/> _Current roles & affiliations_: - PhD student in Linguistics at the National and Kapodistrian University of Athens (NKUA), Lab of Psycholinguistics and Neurolinguistics of NKUA, Greece  - Research Assistant at the Center for Multilingualism Across the Lifespan (MultiLing), University of Oslo, Norway]
