title: Marielena Soilemezidi
logo: /assets/repository-MS_wug.png
description: Current roles & affiliations: PhD student in Linguistics at the National and Kapodistrian University of Athens (NKUA), Lab of Psycholinguistics and Neurolinguistics of NKUA, Greece & Research Assistant at the Center for Multilingualism Across the Lifespan (MultiLing), University of Oslo, Norway
theme: jekyll-theme-minimal
