title: Marielena Soilemezidi
logo: /assets/Soilemezidi_M.jpg
description: PhD student in Linguistics at the National and Kapodistrian University of Athens (NKUA), Lab of Psycholinguistics and Neurolinguistics of NKUA, Athens, Greece & Research Assistant at the Center for Multilingualism Across the Lifespan (MultiLing), University of Oslo, Oslo, Norway
theme: jekyll-theme-minimal
