title: Marielena Soilemezidi
logo: /assets/Soilemezidi_M.jpg
description: PhD student in Linguistics at the National and Kapodistrian University of Athens (NKUA), <br/>Lab of Psycholinguistics and Neurolinguistics of NKUA, <br/>Athens, Greece <br/>& Research Assistant at the Center for Multilingualism Across the Lifespan (MultiLing), University of Oslo, <br/>Oslo, Norway
theme: jekyll-theme-minimal
